//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pompo.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pompo.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The alias &apos;{0}&apos; matches the class name..
        /// </summary>
        internal static string AliasMatchesClassName {
            get {
                return ResourceManager.GetString("AliasMatchesClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The alias ​​should not be a C# keyword..
        /// </summary>
        internal static string AliasMatchesKeyword {
            get {
                return ResourceManager.GetString("AliasMatchesKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The alias &apos;{0}&apos; matches the method name in the class &apos;{1}&apos;..
        /// </summary>
        internal static string AliasMatchesMethodName {
            get {
                return ResourceManager.GetString("AliasMatchesMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The alias must consist of letters, numbers or  _ and can not starts with numbers..
        /// </summary>
        internal static string AliasNotFollowRules {
            get {
                return ResourceManager.GetString("AliasNotFollowRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The alias ​​defined multiple times for the class &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleClassAliasDeclarations {
            get {
                return ResourceManager.GetString("MultipleClassAliasDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not unique class alias &apos;{0}&apos;..
        /// </summary>
        internal static string NotUniqueClassAlias {
            get {
                return ResourceManager.GetString("NotUniqueClassAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The alias &apos;{0}&apos; defined for multiple constructors in the &apos;{1}&apos; class..
        /// </summary>
        internal static string OneAliasForSeveralCtors {
            get {
                return ResourceManager.GetString("OneAliasForSeveralCtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The alias &apos;{0}&apos; defined for multiple methods in the &apos;{1}&apos; class..
        /// </summary>
        internal static string OneAliasForSeveralMethods {
            get {
                return ResourceManager.GetString("OneAliasForSeveralMethods", resourceCulture);
            }
        }
    }
}
