using Pompo.Entities;
using System;
using System.Collections.Generic;
using System.Text;

namespace Pompo
{
    public partial class CodeGenerator
    {
        private string GenerateFactorySourceCode (List<ClassDescription> classes) => $@"/// <summary>
/// The factory for creating objects transmitted to the JS runtime.
/// Generated by Pompo {DateTime.Now}.
/// </summary>

using Microsoft.JSInterop;

{( string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : $"namespace {_props["build_property.RootNamespace"]}" )}
{( string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : "{" )}
    public class Factory(IJSObjectReference jsTransmitModule)
    {{
        private readonly IJSObjectReference _jsTransmitModule = jsTransmitModule;

        private async Task TransmitObject<T>(DotNetObjectReference<T> obj)
            where T: class =>
            await _jsTransmitModule.InvokeVoidAsync(""transmit"", obj);
    }}
{( string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : "}" )}";

        private string GenerateTransmitterSourceCode(List<ClassDescription> classes)
        {
            throw new NotImplementedException();
        }
    }
}