using Pompo.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using Pompo.Extensions;

namespace Pompo
{
    /// <summary>
    /// Generates source code for a object creation factory class, a WebAssemblyHost extension and a JS transmitter.
    /// </summary>
    public partial class CodeGenerator
    {
        /// <summary>
        /// Generates factory source code.
        /// </summary>
        /// <param name="classes">Collection of class declaration.</param>
        /// <returns>Factory source code.</returns>
        private string GenerateFactorySourceCode (List<ClassDescription> classes) => $@"/// <summary>
/// The factory for creating objects transmitted to the JS runtime.
/// Generated by Pompo {DateTime.Now}.
/// </summary>

using Microsoft.JSInterop;

{( string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : $"namespace {_props["build_property.RootNamespace"]}" )}
{( string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : "{" )}
    public class Factory(IJSObjectReference jsTransmitModule, IServiceProvider serviceProvider)
    {{
        private readonly IJSObjectReference _jsTransmitModule = jsTransmitModule;
        private readonly IServiceProvider _serviceProvider = serviceProvider;

        private async Task TransmitObject<T>(DotNetObjectReference<T> obj)
            where T: class =>
            await _jsTransmitModule.InvokeVoidAsync(""transmit"", obj);

        public void InjectServices(object obj)
        {{
            var props = obj.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.SetProperty | System.Reflection.BindingFlags.GetProperty | System.Reflection.BindingFlags.Instance)
                .Where(p => p.GetCustomAttributes(typeof(InjectAttribute), true).Any());

            foreach (var p in props)
            {{
                var s = _serviceProvider.GetService(p.GetGetMethod().ReturnType)
                    ?? throw new ApplicationException($""Unable resolve service {{p.GetGetMethod().ReturnType.FullName}} for property {{obj.GetType().FullName}}.{{p.Name}}"");
                p.SetValue(obj, s);
            }}
        }}
{ GenerateCreateMethodsForFactory(classes) }
    }}
{( string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : "}" )}";

        /// <summary>
        /// Generate object creation methods source code.
        /// </summary>
        /// <param name="classes">Collection of class declaration.</param>
        /// <returns>Source code.</returns>
        private string GenerateCreateMethodsForFactory(List<ClassDescription> classes) => string.Join(
            "\n",
            classes.SelectMany(c => c.Ctors.Select(ctor => $@"
        [JSInvokable]
        public async Task Create_{ctor.TransmitName}({ctor.Parameters}) =>
        {{
            var obj = DotNetObjectReference.Create(new {c.FullName}({ctor.Parameters?.ToJsLikeParameterListString()}));
            InjectServices(obj);
            await TransmitObject(obj);
        }}")));

        /// <summary>
        /// Generates JS transmitter source code.
        /// </summary>
        /// <param name="classes">Collection of class declaration.</param>
        /// <returns>Source code.</returns>
        private string GenerateTransmitterSourceCode(List<ClassDescription> classes) => $@"//////////////////////////////////////////
// The factory for transmit .NET objects.
// Generated by Pompo {DateTime.Now}.
//////////////////////////////////////////
/*
window.transmitFunc = (obj) => {{
    window.dotNetObjectFactory = obj;
    { GenerateCreateMethodsForTransmitter(classes) }
    console.log('Pompo factory initialized.');
}};

export function transmit(obj) {{
    if (window.transmitFunc) {{
        window.transmitFunc(obj);
    }}
}};
*/";

        /// <summary>
        /// Generates objects creation methods source code for JS transmitter.
        /// </summary>
        /// <param name="classes">Collection of class declaration.</param>
        /// <returns>Source code.</returns>
        private string GenerateCreateMethodsForTransmitter(List<ClassDescription> classes) => string.Join(
            "\n",
            classes.SelectMany(c => c.Ctors.Select(ctor => $@"
    window.dotNetObjectFactory.create_{ctor.TransmitName} = async ({ctor.Parameters?.ToJsLikeParameterListString()}) => {{
        let o = null;
        window.transmitFunc = (obj) => o = obj;
        await window.dotNetObjectFactory.invokeMethodAsync(
            'Create_{ctor.TransmitName}'{(string.IsNullOrWhiteSpace(ctor.Parameters?.ToJsLikeParameterListString()) ? string.Empty : $@",
            {ctor.Parameters?.ToJsLikeParameterListString()}")}
        );
{ GenerateMethodInvokes(c) }

        delete window.transmitFunc;
        return o;
    }};"))
        );

        /// <summary>
        /// Generates invoking methods source code for JS transmitter.
        /// </summary>
        /// <param name="cls">Class declaration.</param>
        /// <returns></returns>
        private string GenerateMethodInvokes(ClassDescription cls) => string.Join(
            "\n", cls.Methods.Select(m => $@"
        o.{m.TransmitName} = async ({m.Parameters?.ToJsLikeParameterListString()}) => await o.invokeMethodAsync(
            '{m.Name}'{(string.IsNullOrWhiteSpace(m.Parameters?.ToJsLikeParameterListString()) ? string.Empty : $@",
            {m.Parameters?.ToJsLikeParameterListString()}")}
        );"));

        /// <summary>
        /// Generates WebAssembly host extension source code.
        /// </summary>
        /// <returns>Source code.</returns>
        private string GenerateWebAssemblyHostExtensionCode() => $@"/// <summary>
/// The extension method for WebAssemblyHost.
/// Generated by Pompo {DateTime.Now}.
/// </summary>

using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.JSInterop;

{(string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : $"namespace {_props["build_property.RootNamespace"]}")}
{(string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : "{")}
    public static class WebAssemblyHostExtension
    {{
        public static async Task UsePompoAsync(this WebAssemblyHost host)
        {{
            var serviceProvider = host.Services.GetRequiredService<IServiceProvider>();
            var jsRuntime = host.Services.GetRequiredService<IJSRuntime>();
            var jsTransmitModule = await jsRuntime.InvokeAsync<IJSObjectReference>(""import"", ""./{_props["build_property.PompoJsWrapperOutputFile"]}"");
            var factory = DotNetObjectReference.Create(new Factory(jsTransmitModule, serviceProvider));
            await jsTransmitModule.InvokeVoidAsync(""transmit"", factory);
        }}
    }}
{(string.IsNullOrWhiteSpace(_props["build_property.RootNamespace"]) ? string.Empty : "}")}";
    }
}