/// <summary>
/// The extension method for WebAssemblyHost.
/// Generated by Pompo 14.03.2025 16:36:38.
/// </summary>

using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.JSInterop;

namespace WasmModule
{
    public static class WebAssemblyHostExtension
    {
        public static async Task UsePompoAsync(this WebAssemblyHost host)
        {
            var jsRuntime = host.Services.GetRequiredService<IJSRuntime>();
            var jsTransmitModule = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "./_pompo.js");
            var factory = DotNetObjectReference.Create(new Factory(jsTransmitModule, host.Services));
            await jsTransmitModule.InvokeVoidAsync("transmit", factory);
        }
    }
}